units:
  p: 2
  pU: U + p
  angle: -14
  thumb_splay_angle: -10
  $default_spread: cx
  $default_padding: cy
  m2_screw_radius: 1.6 / 2 # diameter based on mcmaster 99461A913
  m2_hole_radius_pcb: m2_screw_radius * 2.5 # enough plastic around screw to hold strongly
  m2_hole_radius_plate_expand: m2_hole_radius_pcb - (m2_screw_radius + 0.05) # pcb radius - actual desired hole size (enough wiggle room for plate for easy screw inserting and removal)
  m2_hole_radius_insert_expand: m2_hole_radius_pcb - 0.8 * m2_screw_radius # pcb radius - actual desired hole size (80% of screw width, so there is enough material to grab on to)
  pcb_thickness: 1.6
  plate_thickness: 1.2
  plate_switch_hole: 13.9
  wall_thickness: 2
  switch_gap: 5 - plate_thickness # distance from the top of the pcb to the bottom of the plate
  wall_height: 8 - plate_thickness + 0.6 # screw height - plate_thickness + adjustment to allow 2mm space under pcb
  promicro_pos_x: 24
  promicro_pos_y: -9
  promicro_l: 36
  promicro_w: 18.5
  slider_pos_x: 33.5
  slider_pos_y: -31
points:
  zones:
    matrix:
      anchor.shift: [100, -150] # Fix KiCad placement
      columns:
        pinky:
          key:
            column_net: P5
        ring:
          key:
            column_net: P6
            stagger: 7
        middle:
          key:
            column_net: P7
            stagger: 7
        index:
          key:
            column_net: P8
            stagger: -7
        inner:
          key:
            column_net: P9
      rows:
        bottom:
          row_net: P19
        home:
          row_net: P20
        top:
          row_net: P21
    thumb:
      anchor:
        ref: matrix_inner_bottom
        shift: [-0.55U, -U]
      columns:
        inner:
          key:
            shift: [-6, 0]
            column_net: P7
        mid:
          key:
            splay: thumb_splay_angle
            shift: [-4, -2.5]
            column_net: P8
        outer:
          key:
            splay: thumb_splay_angle
            shift: [-1.5, -4.7]
            column_net: P9
      rows:
        key:
          row_net: P18
outlines:
  _true_keys_debug:
    - what: rectangle
      where: true
      size: [18, 18]
  _padded_keys:
    - what: rectangle
      where: true
      size: pU
  _glue_block:
    - what: polygon
      points:
        - ref: matrix_ring_home
          shift: [-0.5pU, 0.5pU]
        - ref: matrix_pinky_bottom
          shift: [-0.5pU, -0.5pU]
        - ref: matrix_pinky_bottom
          shift: [-0.5pU, -0.5pU - 3.5]
        - ref: thumb_outer_key
          shift: [0.5pU, -0.5pU]
        - ref: thumb_outer_key
          shift: [0.5pU, 0.5pU]
        - ref: matrix_inner_top
          shift: [0.5pU + 2p + promicro_w + 2.7, 0.5pU]
        - ref: matrix_inner_top
          shift: [0.5pU, 0.5pU]
  _promicro_slot:
    - what: rectangle
      size: [promicro_l + 10, promicro_w + 10]
      where:
        ref: matrix_inner_top
        shift: [promicro_pos_x + 5, promicro_pos_y + 5]
        rotate: 90
  _slider_slot:
    - what: rectangle
      size: [8.5, 8.5]
      where:
        ref: matrix_inner_top
        shift: [slider_pos_x, slider_pos_y]
  _base_outline: [_padded_keys, _glue_block]
  _pcb_drill:
    - what: circle
      radius: m2_hole_radius_pcb
      where:
        - matrix_pinky_bottom
        - matrix_inner_top
      adjust:
        shift: [0.5*cx, -0.5*cy]
    - what: circle
      radius: m2_hole_radius_pcb
      where:
        - matrix_ring_top
        - thumb_mid_key
      adjust:
        shift: [-0.5*cx, -0.5*cy]
  _top_plate_drill:
    - what: outline
      name: _pcb_drill
      expand: -m2_hole_radius_plate_expand
  _case_standoff_heat_inserts:
    - what: outline
      name: _pcb_drill
      expand: -m2_hole_radius_insert_expand
  _case_standoff_thru:
    - what: outline
      name: _pcb_drill
      expand: -0.1
  _case_standoff:
    - what: circle
      radius: 2
      where: /^.*(pinky|ring|middle|index)_(top|home).*/
      adjust:
        shift: [0.5*cx, -0.5*cy]
    - what: circle
      radius: 2
      where: /^.*(ring|middle|index|inner)_bottom.*/
      adjust:
        shift: [0.5*cx, -0.5*cy]
    - what: circle
      radius: 4
      where: matrix_middle_bottom
      adjust:
        shift: [0, -1.5cy]
  _matrix_outline:
    - what: outline
      name: _base_outline
      fillet: 1
  _case_outline:
    - what: outline
      name: _matrix_outline
      expand: wall_thickness
  _wall_outline: [_case_outline, -_matrix_outline]
  _plate_switch_hole:
    - what: rectangle
      size: [plate_switch_hole, plate_switch_hole]
      where: true
  top_plate_outline:
    [
      _case_outline,
      -_plate_switch_hole,
      -_top_plate_drill,
      -_promicro_slot,
      -_slider_slot,
    ]
  ibkbd_mini_split_pcb: [_matrix_outline, -_pcb_drill]
  debug_view:
    [
      ^_true_keys_debug,
      ^_padded_keys,
      ^_glue_block,
      ^_promicro_slot,
      ^_slider_slot,
      ^_base_outline,
      ^_pcb_drill,
      ^_top_plate_drill,
      ^_case_standoff_heat_inserts,
      ^_case_standoff_thru,
      ^_case_standoff,
      ^_matrix_outline,
      ^_case_outline,
      ^_wall_outline,
      ^_plate_switch_hole,
      ^top_plate_outline,
      ^ibkbd_mini_split_pcb,
    ]
cases:
  bottom_plate:
    - what: outline
      name: _case_outline
      extrude: wall_thickness
    - what: outline
      name: _wall_outline
      extrude: wall_height
      shift: [0, 0, wall_thickness]
    - what: outline
      name: _case_standoff
      operation: add
      extrude: wall_height - pcb_thickness - switch_gap
      shift: [0, 0, wall_thickness]
    - what: outline
      name: _case_standoff_thru
      operation: add
      extrude: wall_height
      shift: [0, 0, wall_thickness]
    - what: outline
      name: _case_standoff_heat_inserts
      operation: subtract
      extrude: wall_height
      shift: [0, 0, wall_thickness]
    - what: outline
      name: _slider_slot
      operation: subtract
      extrude: 15
      shift: [0, 0, wall_thickness + wall_height - switch_gap]
  top_plate:
    - what: outline
      name: top_plate_outline
      extrude: plate_thickness
pcbs:
  ibkbd_mini_split_pcb:
    outlines:
      ibkbd_mini_split_pcb:
        outline: ibkbd_mini_split_pcb
    footprints:
      keys:
        what: choc_with_diode
        where: true
        params:
          from: "{{row_net}}"
          to: "{{column_net}}"
          colrow: "{{colrow}}" # hack
      promicro:
        what: promicro
        where:
          ref: matrix_inner_top
          shift: [promicro_pos_x, promicro_pos_y]
          rotate: -90
      battery:
        what: jstph
        where:
          ref: matrix_inner_top
          shift: [slider_pos_x - 10, slider_pos_y - 10]
          rotate: 180
        params:
          pos: batswitch
          neg: GND
          side: F
      switch_F:
        what: slider
        where:
          ref: matrix_inner_top
          shift: [slider_pos_x, slider_pos_y]
          rotate: -90
        params:
          from: batswitch
          to: RAW
          side: F
      switch_B:
        what: slider
        where:
          ref: matrix_inner_top
          shift: [slider_pos_x, slider_pos_y]
          rotate: -90
        params:
          from: batswitch
          to: RAW
          side: B
