points:
  zones:
    main:
      rotate: -15
      mirror: &mirror
        ref: main_inner_bottom
        shift: 1.5U
      columns:
        pinky:
          key:
            column_net: P4
            mirror.column_net: P9
        ring:
          key:
            column_net: P5
            mirror.column_net: P8
            stagger: 7
        middle:
          key:
            column_net: P6
            mirror.column_net: P7
            stagger: 7
        index:
          key:
            column_net: P7
            mirror.column_net: P6
            stagger: -7
        inner:
          key:
            column_net: P8
            mirror.column_net: P5
      rows:
        bottom:
          row_net: P21
          mirror.row_net: P18
        home:
          row_net: P20
          mirror.row_net: P15
        top:
          row_net: P19
          mirror.row_net: P14
    thumb:
      mirror: &mirror
        ref: main_inner_bottom
        shift: 1.5U
      anchor:
        ref: main_inner_bottom
        shift: [-0.9U,-1.2U]
      columns:
        inner:
          key:
            splay: -10
            shift: [-6,0]
            column_net: P21
            mirror.column_net: P18
        mid:
          key:
            splay: -10
            shift: [-4,-2.5]
            column_net: P20
            mirror.column_net: P15
        outer:
          key:
            splay: -10
            shift: [-1.5,-4]
            column_net: P19
            mirror.column_net: P14
      rows:
        key:
          row_net: P9
          mirror.row_net: P4
