units:
  p: 2
  angle: -14
  thumb_splay_angle: -10
  mirror_dist: 1.25U
  pU: U + p
  $default_spread: cx
  $default_padding: cy
  m2_hole_radius_pcb: 1.1
  m2_hole_insert_radius_expand: 1
  m2_hole_standoff_radius_expand: 1.5
  m2_height: 8 - 1.6 - 1.2 # total screw height - screw head height - adjustment
  pcb_thickness: 1.6
  parts_clearance: 2.5 + 0.8
  plate_thickness: 2
  plate_switch_hole: 13.9
  wall_height: (m2_height - pcb_thickness) + parts_clearance
  wall_thickness: 2
  switch_gap: 0.2
  switch_clip_height: 0.8
  promicro_pos_x: 0
  promicro_pos_y: 5
  promicro_angle: -90
  slider_pos_x: 15
  slider_pos_y: 21
points:
  zones:
    main:
      anchor.shift: [100, -100]
      rotate: angle
      mirror: &mirror
        ref: main_inner_bottom
        shift: mirror_dist
      columns:
        pinky:
          key:
            column_net: P5
        ring:
          key:
            column_net: P6
            stagger: 7
        middle:
          key:
            column_net: P7
            stagger: 7
        index:
          key:
            column_net: P8
            stagger: -7
        inner:
          key:
            column_net: P9
      rows:
        bottom:
          row_net: P19
          mirror.row_net: P14
        home:
          row_net: P20
          mirror.row_net: P15
        top:
          row_net: P21
          mirror.row_net: P18
    thumb:
      mirror: &mirror
        ref: main_inner_bottom
        shift: mirror_dist
      anchor:
        ref: main_inner_bottom
        shift: [-0.55U,-U]
      columns:
        inner:
          key:
            shift: [-6,0]
            column_net: P21
            mirror.column_net: P18
        mid:
          key:
            splay: thumb_splay_angle
            shift: [-4,-2.5]
            column_net: P20
            mirror.column_net: P15
        outer:
          key:
            splay: thumb_splay_angle
            shift: [-1.5,-4.7]
            column_net: P19
            mirror.column_net: P14
      rows:
        key:
          row_net: P4
          mirror.row_net: P4
outlines:
  _padded_keys:
    - what: rectangle
      where: true
      size: pU
  _keys_clip:
    - what: rectangle
      where: true
      size: plate_switch_hole + 0.8 
  _glue_block:
    - what: polygon
      points:
        - ref: main_middle_top
          shift: [0.5pU, 0.5pU]
        - ref: main_pinky_bottom
          shift: [-0.5pU, -0.5pU]
        - ref: thumb_inner_key
          shift: [-0.5pU, -0.5pU]
        - ref: thumb_outer_key
          shift: [0.5pU, -0.5pU]
        - ref: mirror_thumb_outer_key
          shift: [0.5pU, -0.5pU]
        - ref: mirror_thumb_inner_key
          shift: [-0.5pU, -0.5pU]
        - ref: mirror_main_pinky_bottom
          shift: [-0.5pU, -0.5pU]
        - ref: mirror_main_middle_top
          shift: [0.5pU, 0.5pU]
  _promicro_slot:
    - what: rectangle
      size: [34, 18.5]
      where: 
        - aggregate.parts:
            - main_inner_top
            - mirror_main_inner_top
          shift: [promicro_pos_x, promicro_pos_y]
          rotate: promicro_angle
  _slider_slot:
    - what: rectangle
      size: [8.5, 8.5]
      where: 
        - aggregate.parts:
            - main_inner_top
            - mirror_main_inner_top
          shift: [slider_pos_x, slider_pos_y]
          rotate: promicro_angle
  _base_outline:
    - what: outline
      name: _padded_keys
    - what: outline
      name: _glue_block
  _pcb_drill:
    - what: circle
      radius: m2_hole_radius_pcb
      where:
        - aggregate.parts:
          - thumb_outer_key
          - mirror_thumb_outer_key
    - what: circle
      radius: m2_hole_radius_pcb
      where: /^.*ring_home.*/
      adjust:
        shift: [-0.5*cx,-0.5*cy]
    - what: circle
      radius: m2_hole_radius_pcb
      where: /^.*inner_top.*/
      adjust:
        shift: [-0.5*cx,0.75*cy]
  _case_standoff_heat_inserts:
    - what: outline
      name: _pcb_drill
      expand: m2_hole_insert_radius_expand
  _case_standoff:
    - what: outline
      name: _case_standoff_heat_inserts
      expand: m2_hole_standoff_radius_expand
    - what: circle
      radius: 6*m2_hole_radius_pcb
      where:
        - aggregate.parts:
          - main_inner_bottom
          - mirror_main_inner_bottom
    - what: circle
      radius: 2*m2_hole_radius_pcb
      where: /^.*(ring|middle|index|inner)_(top|bottom).*/
      adjust:
        shift: [-0.5*cx,-0.5*cy]
  _main_outline:
    - what: outline
      name: _base_outline
      fillet: 1
  _case_outline:
    - what: outline
      name: _main_outline
      expand: wall_thickness
  _wall_outline:
    - what: outline
      name: _case_outline
    - what: outline
      name: _main_outline
      operation: subtract
  _wall_cutout_for_slider:
    - what: outline
      name: _wall_outline
    - what: outline
      name: _slider_slot
      operation: subtract
      adjust.shift: [0,5]
  top_plate_outline:
    - what: outline
      name: _case_outline
    - what: rectangle
      size: [plate_switch_hole, plate_switch_hole]
      where: true
      operation: subtract
    - what: outline
      name: _pcb_drill
      operation: subtract
    - what: outline
      name: _promicro_slot
      operation: subtract
    - what: outline
      name: _promicro_slot
      adjust.shift: [0,5]
      operation: subtract
  ibkbd_mini_pcb:
    - what: outline
      name: _main_outline
    - what: outline
      name: _pcb_drill
      operation: subtract
  debug_view:
    - what: rectangle
      where: true
      operation: stack
      size: [cx, cy]
    - what: outline
      name: _padded_keys
      operation: stack
    - what: outline
      name: _glue_block
      operation: stack
    - what: outline
      name: _promicro_slot
      operation: stack
    - what: outline
      name: _slider_slot
      operation: stack
    - what: outline
      name: _base_outline
      operation: stack
    - what: outline
      name: _pcb_drill
      operation: stack
    - what: outline
      name: _case_standoff_heat_inserts
      operation: stack
    - what: outline
      name: _case_standoff
      operation: stack
    - what: outline
      name: _main_outline
      operation: stack
    - what: outline
      name: _case_outline
      operation: stack
    - what: outline
      name: _wall_outline
      operation: stack
    - what: outline
      name: _wall_cutout_for_slider
      operation: stack
    - what: outline
      name: top_plate_outline
      operation: stack
    - what: outline
      name: ibkbd_mini_pcb
      operation: stack
cases:
  bottom_plate:
    - what: outline
      name: _case_outline
      extrude: wall_thickness
    - what: outline
      name: _case_standoff
      operation: add
      extrude: wall_height - pcb_thickness - switch_gap
      shift: [0, 0, wall_thickness]
    - what: outline
      name: _case_standoff_heat_inserts
      operation: subtract
      extrude: wall_height - pcb_thickness - switch_gap
      shift: [0, 0, wall_thickness]
    - what: outline
      name: _wall_outline
      extrude: wall_height - parts_clearance - pcb_thickness
      shift: [0, 0, wall_thickness]
    - what: outline
      name: _wall_cutout_for_slider
      shift: [0, 0, wall_thickness]
      extrude: wall_height
  top_plate:
    - what: outline
      name: top_plate_outline
      extrude: plate_thickness
    - what: outline
      name: _keys_clip
      extrude: switch_clip_height
      operation: subtract
pcbs:
  ibkbd_mini_pcb:
    outlines:
      ibkbd_mini_pcb:
        outline: ibkbd_mini_pcb
    footprints:
      via:
        what: via
        where: true
        adjust:
          shift: [0, 8]
        params:
          net: "{{column_net}}"
      keys:
        what: choc
        where: true
        params:
          keycaps: true
          hotswap: true
          reverse: false
          from: "{{colrow}}"
          to: "{{column_net}}"
      diodes_main:
        what: diode
        where: /.*main_.*/
        adjust:
          shift: [0, -5]
        params:
          to: "{{row_net}}"
          from: "{{colrow}}"
      diodes_thumb:
        what: diode
        where: /.*thumb_.*/
        adjust:
          shift: [0, -5]
          rotate: 180
        params:
          to: "{{colrow}}"
          from: "{{row_net}}"
      promicro:
        what: promicro
        where:
          aggregate.parts:
            - main_inner_top
            - mirror_main_inner_top
          shift: [promicro_pos_x, promicro_pos_y]
          rotate: promicro_angle
      battery:
        what: jstph
        where:
          aggregate.parts:
            - main_inner_top
            - mirror_main_inner_top
          shift: [0,-13]
        params:
          pos: batswitch
          neg: GND
          side: B
      switch:
        what: slider
        where:
          aggregate.parts:
            - main_inner_top
            - mirror_main_inner_top
          shift: [slider_pos_x, slider_pos_y]
        params:
          from: batswitch
          to: RAW
          side: B
