units:
  p: 2
  angle: -14
  thumb_splay_angle: -10
  mirror_dist: 1.25U
  mount_radius: 1
  pU: U + p
  $default_spread: cx
  $default_padding: cy
  # todo: fix units with sane values
  wall_height: 4
  promicro_pos_x: 0
  promicro_pos_y: 5
  promicro_angle: -90
  slider_pos_x: 15
  slider_pos_y: 19
points:
  zones:
    main:
      rotate: angle
      mirror: &mirror
        ref: main_inner_bottom
        shift: mirror_dist
      columns:
        pinky:
          key:
            column_net: P5
        ring:
          key:
            column_net: P6
            stagger: 7
        middle:
          key:
            column_net: P7
            stagger: 7
        index:
          key:
            column_net: P8
            stagger: -7
        inner:
          key:
            column_net: P9
      rows:
        bottom:
          row_net: P19
          mirror.row_net: P14
        home:
          row_net: P20
          mirror.row_net: P15
        top:
          row_net: P21
          mirror.row_net: P18
    thumb:
      mirror: &mirror
        ref: main_inner_bottom
        shift: mirror_dist
      anchor:
        ref: main_inner_bottom
        shift: [-0.55U,-U]
      columns:
        inner:
          key:
            shift: [-6,0]
            column_net: P21
            mirror.column_net: P18
        mid:
          key:
            splay: thumb_splay_angle
            shift: [-4,-2.5]
            column_net: P20
            mirror.column_net: P15
        outer:
          key:
            splay: thumb_splay_angle
            shift: [-1.5,-4.7]
            column_net: P19
            mirror.column_net: P14
      rows:
        key:
          row_net: P4
          mirror.row_net: P4
outlines:
  _padded_keys:
    - what: rectangle
      where: true
      size: pU
  _glue_block:
    - what: polygon
      points:
        - ref: main_middle_top
          shift: [0.5pU, 0.5pU]
        - ref: main_pinky_bottom
          shift: [-0.5pU, -0.5pU]
        - ref: thumb_inner_key
          shift: [-0.5pU, -0.5pU]
        - ref: thumb_outer_key
          shift: [0.5pU, -0.5pU]
        - ref: mirror_thumb_outer_key
          shift: [0.5pU, -0.5pU]
        - ref: mirror_thumb_inner_key
          shift: [-0.5pU, -0.5pU]
        - ref: mirror_main_pinky_bottom
          shift: [-0.5pU, -0.5pU]
        - ref: mirror_main_middle_top
          shift: [0.5pU, 0.5pU]
  _promicro_slot:
    - what: rectangle
      size: [39, 18]
      where: 
        - aggregate.parts:
            - main_inner_top
            - mirror_main_inner_top
          shift: [promicro_pos_x, promicro_pos_y]
          rotate: promicro_angle
  _slider_slot:
    - what: rectangle
      size: [8.5, 8.5]
      where: 
        - aggregate.parts:
            - main_inner_top
            - mirror_main_inner_top
          shift: [slider_pos_x, slider_pos_y]
          rotate: promicro_angle
  debug_view:
    - what: rectangle
      where: true
      size: [cx, cy]
      operation: stack
    - what: outline
      name: _padded_keys
      operation: stack
    - what: outline
      name: _glue_block
      operation: stack
    - what: outline
      name: _promicro_slot
      operation: stack
    - what: outline
      name: _slider_slot
      operation: stack
  _base_outline:
    - what: outline
      name: _padded_keys
    - what: outline
      name: _glue_block
  _pcb_drill:
    - what: circle
      radius: mount_radius
      where:
        - aggregate.parts:
          - thumb_outer_key
          - mirror_thumb_outer_key
    - what: circle
      radius: mount_radius
      where: /^.*pinky_bottom.*/
      adjust:
        shift: [0.5*cx,0.5*cy]
    - what: circle
      radius: mount_radius
      where: /^.*index_top.*/
      adjust:
        shift: [-0.5*cx,0.5*cy]
  _case_standoff_heat_inserts:
    - what: outline
      name: _pcb_drill
      expand: 1
  _case_standoff:
    - what: outline
      name: _case_standoff_heat_inserts
      expand: 2.5
  _main_outline:
    - what: outline
      name: _base_outline
      fillet: 1
  _case_outline:
    - what: outline
      name: _main_outline
      expand: 2
  _wall_outline:
    - what: outline
      name: _case_outline
    - what: outline
      name: _main_outline
      operation: subtract
    - what: outline
      name: _promicro_slot
      operation: subtract
      adjust.shift: [0,5]
    - what: outline
      name: _slider_slot
      operation: subtract
      adjust.shift: [0,5]
  top_plate_outline:
    - what: outline
      name: _case_outline
    - what: rectangle
      size: [14, 14]
      where: true
      operation: subtract
    - what: outline
      name: _pcb_drill
      operation: subtract
    - what: outline
      name: _promicro_slot
      operation: subtract
    - what: outline
      name: _promicro_slot
      adjust.shift: [0,5]
      operation: subtract
  ibkbd_mini_pcb:
    - what: outline
      name: _main_outline
    - what: outline
      name: _pcb_drill
      operation: subtract
cases:
  bottom_plate:
    - what: outline
      name: _case_outline
    - what: outline
      name: _case_standoff
      operation: add
      extrude: wall_height - 1
    - what: outline
      name: _case_standoff_heat_inserts
      operation: subtract
      extrude: wall_height - 2
      shift: [0, 0, 1]
    - what: outline
      name: _wall_outline
      extrude: wall_height
      shift: [0, 0, 1]
  top_plate:
    - what: outline
      name: top_plate_outline
      extrude: 1.5
pcbs:
  ibkbd_mini_pcb:
    outlines:
      ibkbd_mini_pcb:
        outline: ibkbd_mini_pcb
    footprints:
      keys:
        what: choc
        where: true
        params:
          keycaps: true
          hotswap: false
          reverse: false
          from: "{{colrow}}"
          to: "{{column_net}}"
      diodes:
        what: diode
        where: true
        adjust:
          rotate: 180
          shift: [0, -5]
        params:
          from: "{{row_net}}"
          to: "{{colrow}}"
      promicro:
        what: promicro
        where:
          aggregate.parts:
            - main_inner_top
            - mirror_main_inner_top
          shift: [promicro_pos_x, promicro_pos_y]
          rotate: promicro_angle
      battery:
        what: jstph
        where:
          aggregate.parts:
            - main_inner_top
            - mirror_main_inner_top
          shift: [0,-13]
        params:
          pos: batswitch
          neg: GND
      switch:
        what: slider
        where:
          aggregate.parts:
            - main_inner_top
            - mirror_main_inner_top
          shift: [slider_pos_x, slider_pos_y]
        params:
          from: batswitch
          to: RAW
