units:
  p: 2
  angle: -14
  thumb_splay_angle: -10
  mirror_dist: 1.25U
  mount_radius: 1
  $default_spread: cx
  $default_padding: cy
points:
  zones:
    main:
      rotate: angle
      mirror: &mirror
        ref: main_inner_bottom
        shift: mirror_dist
      columns:
        pinky:
          key:
            column_net: P5
        ring:
          key:
            column_net: P6
            stagger: 7
        middle:
          key:
            column_net: P7
            stagger: 7
        index:
          key:
            column_net: P8
            stagger: -7
        inner:
          key:
            column_net: P9
      rows:
        bottom:
          row_net: P19
          mirror.row_net: P14
        home:
          row_net: P20
          mirror.row_net: P15
        top:
          row_net: P21
          mirror.row_net: P18
    thumb:
      mirror: &mirror
        ref: main_inner_bottom
        shift: mirror_dist
      anchor:
        ref: main_inner_bottom
        shift: [-0.9U,-1.2U]
      columns:
        inner:
          key:
            splay: thumb_splay_angle
            shift: [-6,0]
            column_net: P21
            mirror.column_net: P18
        mid:
          key:
            splay: thumb_splay_angle
            shift: [-4,-2.5]
            column_net: P20
            mirror.column_net: P15
        outer:
          key:
            splay: thumb_splay_angle
            shift: [-1.5,-4.7]
            column_net: P19
            mirror.column_net: P14
      rows:
        key:
          row_net: P4
          mirror.row_net: P4
outlines:
  padded_keys:
    - what: rectangle
      where: true
      size: U + p
  glue_block:
    - what: polygon
      points:
        - ref: main_middle_top
          shift: [0.5(U + p), 0.5(U + p)]
        - ref: main_pinky_bottom
          shift: [-0.5(U + p), -0.5(U + p)]
        - ref: thumb_inner_key
          shift: [-0.5(U + p), -0.5(U + p)]
        - ref: thumb_outer_key
          shift: [0.5(U + p), -0.5(U + p)]
        - ref: mirror_thumb_outer_key
          shift: [0.5(U + p), -0.5(U + p)]
        - ref: mirror_thumb_inner_key
          shift: [-0.5(U + p), -0.5(U + p)]
        - ref: mirror_main_pinky_bottom
          shift: [-0.5(U + p), -0.5(U + p)]
        - ref: mirror_main_middle_top
          shift: [0.5(U + p), 0.5(U + p)]
  debug_view:
    - what: rectangle
      where: true
      size: U
      operation: stack
    - what: outline
      name: padded_keys
      operation: stack
    - what: outline
      name: glue_block
      operation: stack
  main_outline:
    - what: outline
      name: padded_keys
    - what: outline
      name: glue_block
  mounting:
    - what: circle
      radius: mount_radius
      where:
        - aggregate.parts:
          - main_inner_top
          - mirror_main_inner_top
    - what: circle
      radius: mount_radius
      where:
        - aggregate.parts:
          - thumb_outer_key
          - mirror_thumb_outer_key
    - what: circle
      radius: mount_radius
      where: /^.*ring_home.*/
      adjust:
        shift: [-0.5*cx,0.5*cy]
  ibkbd_mini_pcb:
    - what: outline
      name: main_outline
      fillet: 1
    - what: outline
      name: mounting
      operation: subtract
pcbs:
  ibkbd_mini_pcb:
    outlines:
      ibkbd_mini_pcb:
        outline: ibkbd_mini_pcb
    footprints:
      keys:
        what: choc
        where: true
        params:
          keycaps: true
          hotswap: false
          reverse: false
          from: "{{colrow}}"
          to: "{{column_net}}"
      diodes:
        what: diode
        where: true
        adjust:
          rotate: 180
          shift: [0, -5]
        params:
          from: "{{row_net}}"
          to: "{{colrow}}"
      promicro:
        what: promicro
        where:
          aggregate.parts:
            - main_inner_top
            - mirror_main_inner_top
          shift: [0,5]
          rotate: -90
      battery:
        what: jstph
        where:
          aggregate.parts:
            - main_inner_top
            - mirror_main_inner_top
          shift: [0,-13]
        params:
          pos: batswitch
          neg: GND
      switch:
        what: slider
        where:
          aggregate.parts:
            - main_inner_top
            - mirror_main_inner_top
          shift: [15,19]
        params:
          from: batswitch
          to: RAW
